### ISSUE TITLE
Error: `execute': wrong number of arguments (given 3, expected 1..2) (ArgumentError)         from ./dcsumNew.rb:605:in `block (2 levels) in <main>'

### ISSUE THREAD

**Issue by leecsai** [richmit/dir-inventory#1]
Hi，Richmit

Sorry for blast..

When I tried to test dir-inventory software to initialize the sqlite database, I found this error:

```
[root@node51 bin]# ./dcsumNew.rb -o 123.sqlite /public/exports/dir-1
/usr/local/share/gems/gems/sqlite3-2.0.3/lib/sqlite3/database.rb:199:in `execute': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
        from ./dcsumNew.rb:605:in `block (2 levels) in <main>'
        from /usr/local/share/gems/gems/sqlite3-2.0.3/lib/sqlite3/database.rb:172:in `prepare'
        from ./dcsumNew.rb:604:in `block in <main>'
        from /usr/local/share/gems/gems/sqlite3-2.0.3/lib/sqlite3/database.rb:140:in `initialize'
        from ./dcsumNew.rb:600:in `new'
        from ./dcsumNew.rb:600:in `<main>'
```

I see the error message seems to be that when passing parameters in the program, two parameter values ​​should be passed, but one parameter value is passed in excess. But I see that the 604th line and the following content of the dcsumNew.rb file seem to pass three sets of parameters in each line:
```
  dbCon.prepare( "insert into serrors values (?, ?);" ) do |dbStmtSErrors|
    dbCon.execute( "insert into meta values (?, ?);", 'processStart',            Time.now.to_i)
    dbCon.execute( "insert into meta values (?, ?);", 'csum',                    csumToUse.to_s)
    dbCon.execute( "insert into meta values (?, ?);", 'engine version',          '2020-02-05')
    dbCon.execute( "insert into meta values (?, ?);", 'engine',                  'ruby')
    dbCon.execute( "insert into meta values (?, ?);", 'dirToScan',               dirToScan)
...
```
Is there something wrong with my environment configuration? Or are there some system settings that I did not do correctly?

My environment is: 
```
[root@node51 bin]# cat /etc/redhat-release
CentOS Stream release 9

[root@node51 bin]# ruby --version
ruby 3.0.7p220 (2024-04-23 revision 724a071175) [x86_64-linux]

[root@node51 bin]# sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1
```
pls help me, many thanks!

**Comment by leecsai** [comment]
Please allow me to add a few words. I have just modified all the lines in the dcsumNew.rb file that had the previous error to the following format:
```
  dbCon.prepare( "insert into serrors values (?, ?);" ) do |dbStmtSErrors|
    dbCon.execute( "insert into meta values (?, ?);", ['processStart',            Time.now.to_i])
    dbCon.execute( "insert into meta values (?, ?);", ['csum',                    csumToUse.to_s])
    dbCon.execute( "insert into meta values (?, ?);", ['engine version',          '2020-02-05'])
    dbCon.execute( "insert into meta values (?, ?);", ['engine',                  'ruby'])
...
```
Then I tried to initialize the database again, and it seemed to be successful. 
```
[root@node51 bin]# ./dcsumNew.rb -o 123.sqlite /public/exports/dir-1 -p 35
2024-08-16 22:32:45 : Starting scan: /public/exports/dir-1
2024-08-16 22:32:45 : Collecting scan meta data
2024-08-16 22:32:45 : Scan Starting
//
2024-08-16 22:32:45 : CSUM & DB Write Starting
55
2024-08-16 22:32:45 : Processing Complete
[root@node51 bin]# sqlite3 123.sqlite ".tables"
annofsobj     dirs          ftype2lab     meta          serrors
annofsobjfq   dirsfq        groupmembers  rgroups       users
annometa      fsobj         groups        rusers

[root@node51 bin]# sqlite3 123.sqlite "select * from annofsobjfq"
4|3|4|5|2|0|0|d|16877|subdir-1-1-sub||6|1723818590|1723556762|1723556762|2024-08-16 22:29:50|2024-08-13 21:46:02|2024-08-13 21:46:02|/subdir-1-1/subdir-1-1-sub|/public/exports/dir-1/subdir-1-1/subdir-1-1-sub|root|root
...

[root@node51 bin]# sqlite3 123.sqlite "select * from dirs"
4|4|5|3|2|/subdir-1-1/subdir-1-1-sub
3|3|6|1|1|/subdir-1-1
7|10|11|6|2|/subdir-1-2/subdir-1-2-sub
6|9|12|1|1|/subdir-1-2
...
```

In addition, does this change mean that I have to modify all related dcsumCmp.rb and other execution files? But I feel that this change seems very unprofessional, and I am not sure whether it is correct. Can you please give me a professional solution when you have time?

**Comment by richmit** [comment]
According to the changelog for the sqlite3 ruby gem, this appears to be a change in the sqllite3 API introduced in version 2.0.1 (2024-04-20).  Here is the changelong:

           https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md

I need to do some investigation to see if I can simultaneously support both older and newer versions of the gem in a reasonable way.

**Comment by richmit** [comment]
It appears passing the positional args via an array works for the old version of the GEM as well.  So I've done a quick pass at updating all the execute statement calls with array arguments.  It seems to work on my Debian system with 2.0.4 or with 1.5.3.  Give it a test, and see if it works for you.

-mitch

PS: Thank you for taking the time to report and debug this issue.  I really appreciate it.

**Comment by leecsai** [comment]
I have tested it and there is no problem with the program. Thank you very much.
